### ISSUE TITLE
Specify bounds for slidr activity.

### ISSUE THREAD

**Issue by AKiniyalocts** [r0adkll/Slidr#1]
Thank you for this module! I have been looking for something like this to include in my application.
It would be nice to specify how far from the edge, and which edge we want the swipe to be activated. 
i.e. EDGE_LEFT, EDGE_BOTTOM, LEFT, BOTTOM, etc.

**Comment by r0adkll** [comment]
This is a good idea! I will look into adding this feature.

**Comment by AKiniyalocts** [comment]
@r0adkll awesome! Thank you!

**Comment by r0adkll** [comment]
This has been fixed, use the `SlidrPosition` enum in the `SlidrConfig` when attaching it to an activity
