### ISSUE TITLE
MainActivity not visible while sliding

### ISSUE THREAD

**Issue by nowke** [r0adkll/Slidr#15]
I have 2 activities -> MainActivity & SubActivity. 
Attached Slidr to SubActivity. But while sliding, MainActivity is not visible. When sliding is complete, MainActivity appears. 

Here's the onCreate method of SubActivity

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_add_account);

        SlidrConfig config = new SlidrConfig.Builder()
                .primaryColor(getResources().getColor(R.color.colorPrimary))
                .secondaryColor(getResources().getColor(R.color.colorAccent))
                .position(SlidrPosition.LEFT)
                .sensitivity(1f)
                .build();

        Slidr.attach(this, config);

        // ACTION BAR
        mToolbar = (Toolbar) findViewById(R.id.app_bar);
        setSupportActionBar(mToolbar);
        getSupportActionBar().setHomeButtonEnabled(true);
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

    }

![photo8811761519142839](https://cloud.githubusercontent.com/assets/5479836/6769464/d5823b8e-d0c2-11e4-8c62-420116d295e8.jpg)

**Comment by r0adkll** [comment]
Can you post your theme definition in your styles.xml file and your AndroidManifest.xml?

**Comment by nowke** [comment]
AndroidManifest.xml

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme" >
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".AddAccountActivity"
            android:label="@string/title_activity_add_account"
            android:parentActivityName=".MainActivity" >
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value="in.nowke.expensa.MainActivity" />
        </activity>
    </application>

styles.xml

<resources>

    
    <style name="AppTheme" parent="AppTheme.base">
        
    </style>

    <style name="AppTheme.base" parent="Theme.AppCompat.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="colorControlHighlight">@color/colorHighlight</item>
        <item name="android:windowBackground">@android:color/white</item>
    </style>

</resources>

styles.xml (v21)

    <style name="AppTheme" parent="AppTheme.base">
        <item name="android:colorPrimary">@color/colorPrimary</item>
        <item name="android:colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="android:colorAccent">@color/colorAccent</item>
        <item name="android:colorControlHighlight">@color/colorHighlight</item>
        <item name="android:windowBackground">@android:color/white</item>
    </style>

**Comment by fatihsokmen** [comment]
@nowke Following attributes are missing. Slidr seems to rely on these attributes to work well.
<item name="android:windowIsTranslucent">true</item>  
<item name="android:windowBackground">@android:color/transparent</item>

**Comment by fatihsokmen** [comment]
@nowke Following attributes are missing. Slidr seems to rely on these attributes to work well.
```xml
<item name="android:windowIsTranslucent">true</item>  
<item name="android:windowBackground">@android:color/transparent</item>
```

**Comment by nowke** [comment]
@fatihsokmen That worked out well! Thanks a lot.

**Comment by lance2611** [comment]
I'm having this problem right now yet I've already put these attributes on my theme.

<item name="android:windowIsTranslucent">true</item>  
<item name="android:windowBackground">@android:color/transparent</item>
