### ISSUE TITLE
Undo Slide After Close

### ISSUE THREAD

**Issue by SyedWasiHaider** [r0adkll/Slidr#16]
After a user slides the activity, I show a confirmation dialog. If they click cancel, I need to undo the slide and show the activity again. How can I do this?

**Comment by r0adkll** [comment]
This is beyond the scope of the library and can be implemented in your own application. 

I would look into using the `startActivityForResult(...)` and `onActivityResult(...)` methods in Activity to determine if the user has closed your activity. Then just show the Activity that was slid away using an activity transition if you want it to slide back.
