### ISSUE TITLE
When I slide the activity, the background shows the home screen

### ISSUE THREAD

**Issue by w9xhc** [r0adkll/Slidr#18]
This is my code:
```java
public class MyActivity extends ActionBarActivity {
  public void onCreate(Bundle savedInstanceState) {
      ...
      if (currentapiVersion >= android.os.Build.VERSION_CODES.HONEYCOMB) {
            SlidrConfig config = new SlidrConfig.Builder()
                    .position(SlidrPosition.LEFT)
                    .sensitivity(0.3f)
                    .build();
            Slidr.attach(this, config);
        }
      ...
  }
}
```
***theme.xml***
```java
<style name="MyTheme" parent="AppTheme">
  <item name="android:windowIsTranslucent">true</item>
  <item name="android:windowBackground">@android:color/transparent</item>
</style>
```

***In the layout, I set the background to #ffffff.***

That's all !

I check the slidr lib codes:
```java
ViewGroup decorView = (ViewGroup)activity.getWindow().getDecorView();
View oldScreen = decorView.getChildAt(0);
```
I guess that oldScreen is transparent and empty or oldScreen is home screen.

**Comment by r0adkll** [comment]
Can you tell me what device you were experiencing this on? I've come across this issue once before and I've been trying to narrow it down.

**Comment by w9xhc** [comment]
@r0adkll I have solved this problem.
The cause of the issue is: **the lowest Activity (for example MainActivity), cannot be transparent**.
So I **set the lowest Activity theme to this:**
```java
<style name="MyTheme.NoTransparent" parent="AppTheme" >
        <item name="android:windowIsTranslucent">false</item>
        <item name="android:windowBackground">@color/black</item>
</style>
```
and **set default theme to *\<application/\>* tag in AndroidManifest.xml:**
```java
<style name="MyTheme" parent="AppTheme">
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowBackground">@android:color/transparent</item>
</style>
```
I try to set ```getWindow().getAttributes().alpha = 0.0f; ```in java code, but is not work. 
Finally I set up two different theme to solve this.
It's worked.

@r0adkll Thank you very much for the code. It is low coupling and easy to use.
