### ISSUE TITLE
Disable window dimm

### ISSUE THREAD

**Issue by sergeyfitis** [r0adkll/Slidr#19]
How I can disable window dim? Make window background fully transparent.

**Comment by r0adkll** [comment]
There is currently no way to do this as of now. But I will add it into the next release.

**Comment by sergeyfitis** [comment]
Okay, thank you. I will wait for an update.

**Comment by r0adkll** [comment]
Sorry for the delay on this. But I have fixed the issue in the latest build and will be pushing to Maven here soon.

You can achieve this functionality by setting in the [SlidrConfig](https://github.com/r0adkll/Slidr/blob/master/library%2Fsrc%2Fmain%2Fjava%2Fcom%2Fr0adkll%2Fslidr%2Fmodel%2FSlidrConfig.java) - `.scrimStartAlpha(0f)` and `.scrimEndAlpha(0f)` in the Builder
