### ISSUE TITLE
Transparent activity in adnroid 4.4.2

### ISSUE THREAD

**Issue by Sullivan72** [r0adkll/Slidr#22]
In Android 4.4.2 causing the main activity to "fall behind" the OS view when using NavUtils for up-navigation to the main activity.
I searched on StackOverflow, and thought android:theme="@android:style/Theme.Translucent.NoTitleBar" can help, but in my case I need AppCompat theme and AppCompat haven't tpansparent theme.

**Comment by r0adkll** [comment]
Please read the Readme file in the repository. You don't need a specific translucent theme, you just have to add the following values to your theme:

```xml
<item name="android:windowIsTranslucent">true</item>  
<item name="android:windowBackground">@android:color/transparent</item>
```
