### ISSUE TITLE
Change helper.cancel() to helper.abort() in lock/unlock method.

### ISSUE THREAD

**Issue by ladjzero** [r0adkll/Slidr#24]
I wish to change `mDragHelper.cancel();` to `mDragHelper.abort();` in lock/unlock method because the following case.

I use pullToRrefresh listview and Slidr in an activity. I lock Slidr when listView is pulled to refresh and unlock when the touch is released. Unfortunately, Slidr will eat the first touch event after being unlocked. That means I can not scroll the listview, but only to slide the whole view.

Even though Slidr is disabled, the dragHelper is still tracking touch event silently. `onInterceptTouchEvent` of SlidrPanel may return true once Slidr is enabled and touch occurs.

It is a bit confusing because I did not drag at all after unlocking Slidr.

So, how about calling `abort` to clean touch history instead of `cancel` in lock/unlock method?

**Comment by r0adkll** [comment]
Okay I have changed `.cancel()` to `.abort()` and you can test it by using the Snapshot dependency. Instructions for including that dependency can be found on the README

**Comment by ladjzero** [comment]
Thank you. I'll try.

**Comment by r0adkll** [comment]
@ladjzero Have you had any success with the changes?

**Comment by ladjzero** [comment]
Sorry to reply too late.
It works perfectly!
