### ISSUE TITLE
SNAPSHOT build

### ISSUE THREAD

**Issue by jjhesk** [r0adkll/Slidr#27]
I had an issue from the build.

It looks like this.

Error:Failed to resolve: com.android.support:support-v4:22.2.1
<a href="install.m2.repo">Install Repository and sync project</a><br><a href="openFile">Open File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

i think i am using 

    compile 'com.android.support:support-annotations:22.2.0'
    compile 'com.android.support:support-v13:22.2.0'
    compile 'com.android.support:appcompat-v7:22.2.0'

for all my modules.

what do i need to change in order to match to your configuration?

**Comment by r0adkll** [comment]
I think you just need to update the Android Support Repository and Android Support Library in your SDK Manager

<img width="531" alt="screenshot 2015-08-19 13 49 54" src="https://cloud.githubusercontent.com/assets/1237372/9364268/7208f6c4-4679-11e5-9a0f-6474410486a9.png">
)

**Comment by jjhesk** [comment]
i have notice that. Do I need to change all other library uses com.android.support:* as dependencies to 22.2.1 ?

**Comment by r0adkll** [comment]
Sorry for the late reply. No, I don't think you should have to change your other dependency versions, however you probably should to get the bug fixes and patches in those update versions.
