### ISSUE TITLE
Change status bar color dynamically

### ISSUE THREAD

**Issue by davideas** [r0adkll/Slidr#30]
Hello, thank you for the great library, I've the necessity to change the status bar color dynamically but this has an impact on your library as well since the status bar is set at the beginning when calling _attach()_ and we cannot change it.
I'm using a ViewPager with fragments that dynamically regenerate the color of the status bar using **Palette** library based on the image displayed in each fragment, so this new color should be reflected in **Slidr** library as well.

I've tried to reattach when new color is regenerated, but it has weird behaviour... better to not explain.
I've seen the _replace()_ function but how to use it? we should pass a new ViewGroup, what it should be?

Probably it's much better to update the primary/secondary color of the status bar instead of recreating everything. (Maybe these 2 colors could be static property in _Slidr_ class so we can call _set()_ everywhere, what do you think?).
If you agree I can do that change, but also put in common some code that now is repeated in many functions.

**Comment by r0adkll** [comment]
the `replace()` function is very very experimental right now so I would not use that. I will look into implementing the functionality you need as I don't think it would be a bad thing to be able to dynamically change all the configurable values at runtime if the developer so wanted.

This could probably achieve this my creating _setters_ in the `SlidrConfig` class to allow you to change the values dynamically. This would allow you to change the colors the mechanism interpolates between. 

Feel free to create a pull request or I can make the change here in the next day or two

**Comment by davideas** [comment]
Ok for `SlidrConfig`. I can work this evening on it.

**Comment by davideas** [comment]
if `SlidrConfig` has setters it must be a member of the class `Slidr`. But Slidr has all methods declared _static_. How do you want I proceed? I can make SlidrConfig a static member in Slidr or change Slidr removing static but this is not backward compatible (you should go for a version 3), so maybe better to keep static member in this moment for version 2.1.0.

**Comment by davideas** [comment]
Also I've reviewed the build.gradle files to better manage versions of imported libraries. You will see and keep if you like it.

**Comment by r0adkll** [comment]
I'm not going to remove the static methods from the `Slidr` class as that is one of my requirements of this library. The `SlidrConfig` class does not need to be a static member of the Slidr class (this is bad for a number of reasons). 

All you should need to do is add setters to `SlidrConfig` and keep a reference to your configuration in your activity that you're attaching it to and then change/set the values from there.

**Comment by davideas** [comment]
Ok I understood. So I did it. If you don't like something I will review it.

**Comment by r0adkll** [comment]
I just pushed the added setters to the config and updated the example project to demonstrate it. I also pushed these changes to the snapshot repository: `2.0.5-SNAPSHOT` as well.

**Comment by davideas** [comment]
Hi, for me it is working as well. I close it.
