### ISSUE TITLE
Standart window animation when using Slidr

### ISSUE THREAD

**Issue by Remie-l** [r0adkll/Slidr#33]
Is it possible to use custom window animation with Slidr?
For now using windowIsTranslucent sets animation to default.

```
<item name="android:windowAnimationStyle">@style/Animation.MyAnimation</item>

<item name="android:windowIsTranslucent">true</item>
<item name="android:windowBackground">@android:color/transparent</item>
```

**Comment by SSSSHIELD** [comment]
I have seem problem ,my activity switch Animations are replaced by Android's default Animation..............

**Comment by SSSSHIELD** [comment]
I just solved my problem.
` <style name="notrans" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="android:textColorPrimaryInverse">@color/color_37a991</item>
        <item name="android:windowBackground">@color/color_ededed</item>
    </style>`
And this,my custom Animations are worked.

**Comment by g19980115** [comment]
You can use`<style name="Animation_Activity" parent="@android:style/Animation.Translucent">
//do something
</style>`override the "Animation.Translucent."

**Comment by r0adkll** [comment]
You can also programmatically override the animations to use your own via <a href="https://developer.android.com/reference/android/app/Activity.html#overridePendingTransition(int, int)">overridePendingTransition(int, int)</a>
