### ISSUE TITLE
application  stop/cress 

### ISSUE THREAD

**Issue by Imakerinfosoft** [r0adkll/Slidr#36]
04-18 11:31:24.799 5271-5271/? E/cutils-trace: Error opening trace file: No such file or directory (2)
04-18 11:31:24.835 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:24.841 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:24.843 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:24.843 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:24.843 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:24.845 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:31:24.872 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:31:25.016 5271-5271/? E/memtrack: Couldn't load memtrack module (No such file or directory)
04-18 11:31:25.016 5271-5271/? E/android.os.Debug: failed to load memtrack module: -2
04-18 11:31:27.250 5300-5300/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.r0adkll.slidr.example, PID: 5300
                                                 java.lang.NoClassDefFoundError: org.jacoco.agent.rt.internal_773e439.Offline
                                                     at com.r0adkll.slidr.model.SlidrPosition.$jacocoInit(SlidrPosition.java)
                                                     at com.r0adkll.slidr.model.SlidrPosition.<clinit>(SlidrPosition.java)
                                                     at com.r0adkll.slidr.example.ViewerActivity.onCreate(ViewerActivity.java:64)
                                                     at android.app.Activity.performCreate(Activity.java:5264)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                     at android.os.Handler.dispatchMessage(Handler.java:110)
                                                     at android.os.Looper.loop(Looper.java:193)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                     at dalvik.system.NativeStart.main(Native Method)
04-18 11:31:27.744 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:27.744 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:28.202 932-4876/? E/TelephonyProvider: iTelephony is null!!!
04-18 11:31:28.202 932-4876/? E/TelephonyProvider: iTelephony is null!!!
04-18 11:31:34.493 5367-5367/com.r0adkll.slidr.example E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.r0adkll.slidr.example, PID: 5367
                                                                         java.lang.NoClassDefFoundError: org.jacoco.agent.rt.internal_773e439.Offline
                                                                             at com.r0adkll.slidr.model.SlidrPosition.$jacocoInit(SlidrPosition.java)
                                                                             at com.r0adkll.slidr.model.SlidrPosition.<clinit>(SlidrPosition.java)
                                                                             at com.r0adkll.slidr.example.ViewerActivity.onCreate(ViewerActivity.java:64)
                                                                             at android.app.Activity.performCreate(Activity.java:5264)
                                                                             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                                             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                                                                             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
                                                                             at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                             at android.os.Looper.loop(Looper.java:193)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                             at dalvik.system.NativeStart.main(Native Method)
04-18 11:31:35.441 932-1163/? E/TelephonyProvider: iTelephony is null!!!
04-18 11:31:35.441 932-1163/? E/TelephonyProvider: iTelephony is null!!!
04-18 11:31:39.912 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:39.922 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:39.924 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:39.924 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:39.924 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:39.928 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:31:39.972 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:31:54.876 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:54.882 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:54.886 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:31:54.891 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:54.891 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:54.891 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:31:54.914 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:32:02.275 654-672/? E/CellLocation: create GsmCellLocation
04-18 11:32:02.277 897-18337/? E/CellLocation: create GsmCellLocation
04-18 11:32:02.280 897-1175/? E/CellLocation: create GsmCellLocation
04-18 11:32:02.295 654-654/? E/CellLocation: create GsmCellLocation
04-18 11:32:02.299 897-1175/? E/CellLocation: create GsmCellLocation
04-18 11:32:09.137 654-8466/? E/CellLocation: create GsmCellLocation
04-18 11:32:09.147 654-654/? E/CellLocation: create GsmCellLocation
04-18 11:32:09.882 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:09.892 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:09.894 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:09.896 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:32:09.899 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:09.900 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:09.922 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:32:24.985 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:24.992 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:24.994 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:24.995 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:32:24.999 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:24.999 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:25.021 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:32:26.513 5443-5443/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.r0adkll.slidr.example, PID: 5443
                                                 java.lang.NoClassDefFoundError: org.jacoco.agent.rt.internal_773e439.Offline
                                                     at com.r0adkll.slidr.model.SlidrPosition.$jacocoInit(SlidrPosition.java)
                                                     at com.r0adkll.slidr.model.SlidrPosition.<clinit>(SlidrPosition.java)
                                                     at com.r0adkll.slidr.example.ViewerActivity.onCreate(ViewerActivity.java:64)
                                                     at android.app.Activity.performCreate(Activity.java:5264)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1088)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2390)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                     at android.os.Handler.dispatchMessage(Handler.java:110)
                                                     at android.os.Looper.loop(Looper.java:193)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                     at dalvik.system.NativeStart.main(Native Method)
04-18 11:32:30.517 654-664/? E/CellLocation: create GsmCellLocation
04-18 11:32:30.518 897-13216/? E/CellLocation: create GsmCellLocation
04-18 11:32:30.523 897-1175/? E/CellLocation: create GsmCellLocation
04-18 11:32:30.539 654-654/? E/CellLocation: create GsmCellLocation
04-18 11:32:30.543 897-1175/? E/CellLocation: create GsmCellLocation
04-18 11:32:39.891 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:39.897 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:39.900 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:32:39.901 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:39.904 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:39.904 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:39.924 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:32:53.138 654-8466/? E/CellLocation: create GsmCellLocation
04-18 11:32:53.146 897-915/? E/CellLocation: create GsmCellLocation
04-18 11:32:53.149 654-654/? E/CellLocation: create GsmCellLocation
04-18 11:32:53.152 897-1175/? E/CellLocation: create GsmCellLocation
04-18 11:32:53.169 897-1175/? E/CellLocation: create GsmCellLocation
04-18 11:32:54.887 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:54.894 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:54.894 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:54.894 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:54.895 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:32:54.898 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:32:54.920 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:32:59.091 7136-5487/? E/NativeCrypto: ssl=0x63df5748 cert_verify_callback x509_store_ctx=0x624d0938 arg=0x0
04-18 11:32:59.091 7136-5487/? E/NativeCrypto: ssl=0x63df5748 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
04-18 11:33:09.903 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:09.909 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:09.912 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:33:09.915 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:09.916 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:09.916 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:09.937 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:33:21.387 654-665/? E/CellLocation: create GsmCellLocation
04-18 11:33:21.399 897-1120/? E/CellLocation: create GsmCellLocation
04-18 11:33:21.404 654-654/? E/CellLocation: create GsmCellLocation
04-18 11:33:21.409 897-1175/? E/CellLocation: create GsmCellLocation
04-18 11:33:21.432 897-1175/? E/CellLocation: create GsmCellLocation
04-18 11:33:24.897 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:24.903 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:24.906 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:33:24.909 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:24.910 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:24.910 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:24.931 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:33:39.898 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:39.905 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:39.907 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:39.908 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:39.909 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:33:39.912 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:39.932 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:33:54.900 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:54.906 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:54.909 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:33:54.912 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:54.912 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:54.913 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:33:54.934 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:34:07.788 654-664/? E/CellLocation: create GsmCellLocation
04-18 11:34:07.804 654-654/? E/CellLocation: create GsmCellLocation
04-18 11:34:09.903 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:09.908 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:09.909 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:09.909 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:09.909 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:09.911 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:34:09.931 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:34:24.958 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:24.968 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:24.972 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:34:24.975 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:24.975 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:24.975 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:25.018 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:34:36.237 932-4877/? E/TelephonyProvider: iTelephony is null!!!
04-18 11:34:36.237 932-4877/? E/TelephonyProvider: iTelephony is null!!!
04-18 11:34:36.270 654-672/? E/CellLocation: create GsmCellLocation
04-18 11:34:36.276 932-7043/? E/TelephonyProvider: iTelephony is null!!!
04-18 11:34:36.277 932-7043/? E/TelephonyProvider: iTelephony is null!!!
04-18 11:34:36.306 654-654/? E/CellLocation: create GsmCellLocation
04-18 11:34:36.334 3200-3200/? E/ActivityThread: Failed to find provider info for com.android.tinno.theme.Provider
04-18 11:34:36.430 3200-3200/? E/ActivityThread: Failed to find provider info for com.android.tinno.theme.Provider
04-18 11:34:40.033 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:40.038 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:40.039 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:40.039 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:40.040 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:40.041 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:34:40.061 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:34:55.013 7136-7136/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:55.019 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:55.022 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:55.023 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:55.024 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
04-18 11:34:55.027 654-654/? E/RemoteViews: ANR Warning,RemoteViews can only be used once ,if not ,it may cause ANR in hosts such as Laucher,SystemUI. keys for search <ANR Exception MSG   History>
04-18 11:34:55.048 732-732/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)

**Comment by r0adkll** [comment]
Duplicate: https://github.com/r0adkll/Slidr/issues/35
