### ISSUE TITLE
Previous activity doesn't show

### ISSUE THREAD

**Issue by lance2611** [r0adkll/Slidr#37]
![screenshot_20160501-171728](https://cloud.githubusercontent.com/assets/10286806/14941047/08fc0862-0fc1-11e6-912d-5bd2612c8c80.png)

Java code: 
`protected void onCreate(Bundle savedInstanceState) {`
`super.onCreate(savedInstanceState);`
`setContentView(R.layout.activity_client_detail);`
`Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);`
`setSupportActionBar(toolbar);`
`getSupportActionBar().setHomeButtonEnabled(true);`
`getSupportActionBar().setDisplayHomeAsUpEnabled(true);`
`SlidrConfig config = new SlidrConfig.Builder()`
        `.scrimEndAlpha(0f)`
        `.scrimStartAlpha(0.5f)`
        `.build();`
`Slidr.attach(this, config);`
`}`

Theme:

`<style name="AppTheme.Slidr" parent="@style/AppTheme">
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowBackground">@android:color/transparent</item>
    </style>`

**Comment by muhrifqii** [comment]
I got the same issue, but with transparent background, making the android home screen visible. Anyone?

**Comment by haydarai** [comment]
Have you add parent activity in manifest?

**Comment by muhrifqii** [comment]
yes I have

**Comment by SSSSHIELD** [comment]
@muhrifqii 
I have the same problem.But I just deal with it.
The reason you could see android home screen is that the APP's background is transparent.so,you can set a app:theme on the HomeActivity in mainfest,and the style's attributes ,you can't set <item name="android:windowIsTranslucent">true</item> <item name="android:windowBackground">@android:color/transparent</item>.you must set your app's normally attributes,such as , <item name="android:windowIsTranslucent">false</item> <item name="android:windowBackground">@android:color/red</item>...and this could help you .      OR:you can disallowed  Slidr on your HomeActivity.

**Comment by PragneshNumberTank** [comment]
its' not working in android 4.4.2

**Comment by RomanTsekhmeistruk** [comment]
try to add the next theme to your slideable acivity in manifest:
```
<style name="Theme.Slidr.Slidable" parent="Theme.AppCompat.Light.NoActionBar">
        <!-- These values must be set for this mechanism to work -->
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowBackground">@android:color/transparent</item>

        <item name="android:windowDrawsSystemBarBackgrounds">true</item>
        <item name="android:statusBarColor">@android:color/transparent</item>
    </style>
```

**Comment by bhargavms** [comment]
@haydarai you dont need to add parent activity in xml for this library to work :)

**Comment by bhargavms** [comment]
@RomanTsekhmeistruk thanks for statusbar fix trick :)
