### ISSUE TITLE
Could not find com.r0adkll:slidableactivity

### ISSUE THREAD

**Issue by MahdiPishguy** [r0adkll/Slidr#41]
why i got this error:
```Error:Could not find com.r0adkll:slidableactivity:2.0.6-SNAPSHOT.```

> compile 'com.r0adkll:slidableactivity:2.0.5'
> 
> For Snapshots, include these lines in your gradle files:
> 
> repositories {
>     jcenter()
>     maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
> }
>

**Comment by r0adkll** [comment]
That snapshot is not currently available

**Comment by MahdiPishguy** [comment]
could you help me on this issue : https://github.com/r0adkll/Slidr/issues/42
