### ISSUE TITLE
 swipe directly on single line

### ISSUE THREAD

**Issue by MahdiPishguy** [r0adkll/Slidr#42]
when i swipe left to right not in single line, activity can swipe to close, but i don't like that, i would line to swipe for example left to right on single line directly, how can fix this problem?

http://rupload.ir/upload/rca7hvidvwimzqwm04b1.png

i expect thats VERTICAL but it is not single line as directly left to right

**Comment by r0adkll** [comment]
Certainly! I'm currently looking into this issue at the moment
