### ISSUE TITLE
Only left swipe

### ISSUE THREAD

**Issue by GGLabCenter** [r0adkll/Slidr#45]
Hi,
I sent an email to you with details. Btw, shortly this is:
if I try to scroll up/down the activity with my finger, the library intercepts the few deltax I do with that action and starts moving the screen. The correct behavior should be that if I set: LEFT, only if I swipe exactly from left it works, and not also if I do diagonals motions. Please fix this problem, and thanks for the beautiful library. Another improvement should the possibility to use the library not only with activities but with fragments. Best regards

**Comment by GGLabCenter** [comment]
Sorry i read only now that the issue is the same of #42 .

**Comment by MahdiPishguy** [comment]
@GGLabCenter did you test to know resolved?

**Comment by GGLabCenter** [comment]
I still not resolved by myself the problem, because I read in your issue ~two weaks ago, the author writed that he's working on that, so I gave priority to other things in my project. If necessary in next future I will try to fix by myself... I took a look to the code of the library and I read somewhere on stackoverflow that the only way to calculate the correct line pendency is adding a GestureDetector.OnGestureListener.. 
Maybe also (I thought) modifying something here (SlidrPanel.java), by managing the MotionEvent object:

```
 @Override
    public boolean onInterceptTouchEvent(MotionEvent ev) {
        boolean interceptForDrag = false;

        if(mIsLocked){
            return false;
        }

        if(mConfig.isEdgeOnly()) {
            mIsEdgeTouched = canDragFromEdge(ev);
        }

        // Fix for pull request #13 and issue #12
        try {
                interceptForDrag = mDragHelper.shouldInterceptTouchEvent(ev);
        } catch (Exception e) {
            interceptForDrag = false;
        }

        return interceptForDrag && !mIsLocked;
    }

@Override
    public boolean onTouchEvent(MotionEvent event) {
        if(mIsLocked){
            return false;
        }

        try {
            mDragHelper.processTouchEvent(event);
        }catch (IllegalArgumentException e){
            return false;
        }

        return true;
    }
```

Let's see
PS: i would really need the same usage on fragments.. (as I understand I could be used on views in general because it works with a DrawViewHelper object)

**Comment by r0adkll** [comment]
The difficulty with this issue is that the `ViewDragHelper` class completely handles the logic around when and when not to grab the view and start a drag. There is no direct way to modify this behavior other than playing with the sensitity (which you can define in the `SlidrConfig` class) which modifies the `touchSlop` (which you can see [here](https://android.googlesource.com/platform/frameworks/support/+/2d9e33a/v4/java/android/support/v4/widget/ViewDragHelper.java#362)) which basically dictates the amount of travel a gesture has to go to engage the drag helper. 

What needs to be done is to replace [this method](https://android.googlesource.com/platform/frameworks/support/+/2d9e33a/v4/java/android/support/v4/widget/ViewDragHelper.java#1293) to include checking the `dy` slop on horizontal dragging setups (where it only checks the dx). So I've been researching a way to do this without having to clone the entire class to add this functionality, which is ultimately what I may have to do.

@GGLabCenter Adding Fragments/Generic View support is on my roadmap and I do plan on adding support

**Comment by GGLabCenter** [comment]
Hi, I need that behavior, so I will try to fix that by myself using your suggestion. Could you please give me some tip for the usage of your library also with fragments? I need to implement also this thing. Thanks in advance.

**Comment by ahgpoug** [comment]
Faced the same issue.
This thread has been open since July. Are there any workarounds for now?

**Comment by MahdiPishguy** [comment]
@GGLabCenter this problem resolved on telegram application, i tested that on swipe only right to close activity and work fine

**Comment by GGLabCenter** [comment]
Yes on Telegram that behavior has been always correct (I wanted to emulate it!). But there are hundreds of files with 10k+ rows in the source code.. I avoid to dig into it when possible :-)

**Comment by ahgpoug** [comment]
@MahdiPishguy as I read, Telegram uses their own implementation of fragments. You can read [https://stackoverflow.com/a/25232057/5995606](here) about it. This one library is awesome, except this point. It will be really cool if author implement this feature.

**Comment by GGLabCenter** [comment]
About the horizontal/vertical issue when scrolling, here is my working code to fix the issue:

```
private boolean checkTouchSlop(View child, float dx, float dy) {
        if (child == null) {
            return false;
        }
        final boolean checkHorizontal = mCallback.getViewHorizontalDragRange(child) > 0;
        final boolean checkVertical = mCallback.getViewVerticalDragRange(child) > 0;
        
        float temp_dy = dy;
        if(temp_dy<0)
            temp_dy = -temp_dy;
        
        if (checkHorizontal && checkVertical) {
            return dx * dx + dy * dy > mTouchSlop * mTouchSlop;
        } else if (checkVertical) {
            return Math.abs(dy) > mTouchSlop;
        } else if (checkHorizontal && 2*temp_dy < dx) {
            return Math.abs(dx) > mTouchSlop;
        }
        
        return false;
    }
```
I just used my version of the ViewDragHelper as suggested. It is exactly the same class except made for this method. Now it seems to work like a charm. I will try to mod the library also to work with fragment now.

**Comment by MahdiPishguy** [comment]
@GGLabCenter could you update library by commit this fixed issue?

**Comment by GGLabCenter** [comment]
I do not think to have permissions to edit the library, am I wrong?

**Comment by MahdiPishguy** [comment]
@GGLabCenter maybe you don't have permission, but you can fork this repository and update and and then you can send PL

**Comment by GGLabCenter** [comment]
I did a fork with my few changes, thanks for the hint. I tested it on my Android device and now it is perfectly working as expected. When I will be able to let the library work also with fragments I will update that fork. Have a nice day.

**Comment by MahdiPishguy** [comment]
@GGLabCenter Thanks, you can push this changes on your repository and let us to check that now :) 👍

**Comment by GGLabCenter** [comment]
Hi, I added the same behavior to Fragments also. You can check my repository. I wrote to r0adkll to inform him about this. I will close this issue. Best regards

**Comment by GGLabCenter** [comment]
Done! I hope all correctly, this is the first time I use github to give a contribution. Thanks

**Comment by ahgpoug** [comment]
@GGLabCenter can you upload your fork to any remote repository like Maven or any other? I really don't want to clone entiry repository into my project, but you made a great job. I've tried to add it using Jitpack 
`compile 'com.github.GGLabCenter:Slidr:master-SNAPSHOT'`
but it doesn't work. Thanks in advance.

**Comment by MahdiPishguy** [comment]
@ahgpoug pull request doesn't merge by library owner yet

**Comment by ahgpoug** [comment]
@MahdiPishguy I see it. But we don't really know when owner will approve it. So I advised to connect his own fork at any remote repo to use it without having a whole project inside my repo.

**Comment by MahdiPishguy** [comment]
@ahgpoug the library owner commented 4 days ago, https://github.com/r0adkll/Slidr/issues/45#issuecomment-347879828 and he want to approve it

**Comment by GGLabCenter** [comment]
Hello, don't worry @ahgpoug: we waited several months for these improvements, I think we can wait some more day. I am sure @r0adkll will finish the merge as he has time. If this won't happen, again don't worry, I will try to upload my fork on maven (or wherever). I also tried with jitpack, strange.. it doesn't work also for me. Have a nice day

**Comment by ahgpoug** [comment]
@MahdiPishguy ohhhh, my bad. I really missed this comment. Have no idea how can I be so blind.

**Comment by r0adkll** [comment]
Yes, sorry for the delays here as my day job keeps me pretty busy. I will get this reviewed and merged today!

**Comment by MahdiPishguy** [comment]
@r0adkll no problem, we wait to merge this fix and updating mater repository such as `maven` and `gradle` 👍

**Comment by r0adkll** [comment]
Okay, this has been merged and released to Maven Central, which should take 0-2hrs to propagate. Version **2.0.6**

Thank you for your patience and hard work!
