### ISSUE TITLE
Update the documentation and the code.

### ISSUE THREAD

**Issue by Alexrs95** [r0adkll/Slidr#5]
The latest version of the library (1.0.1) works in a different way as it's indicated in the README. To attach the Slider to the Activity the code is:

```JAVA
SlidableAttacher.attach(this);
```

Additionally, the class SliderAttacher can not be found in the code published on GitHub.

**Comment by r0adkll** [comment]
This is from the old version (1.0.1), the new version [2.0.1](http://search.maven.org/#artifactdetails|com.r0adkll|slidableactivity|2.0.1|) is correct with the documentation.
