### ISSUE TITLE
小米手机,侧滑直接显示透明的

### ISSUE THREAD

**Issue by dh1314al** [r0adkll/Slidr#50]
只有小米的手机这样,其他的手机测试正常。麻烦抽时间修复一下这个问题，谢谢了

**Comment by shoushuai** [comment]
android p 都会这样吧

**Comment by shoushuai** [comment]
android p 都会这样吧

**Comment by r0adkll** [comment]
I'm not sure what is being asked here as Google Translate doesn't help me much.
