### ISSUE TITLE
android8.0 compatibility problem

### ISSUE THREAD

**Issue by shexiaoheng** [r0adkll/Slidr#57]
version : Android 8.0
exception: `Only fullscreen opaque activities can request orientation`
reason:  `<item name="android:windowIsTranslucent"> true </item>`
the solution is not found , can you fix it ?

**Comment by shoushuai** [comment]
![ac67e9326a5e15fb84da15c1e0dd0a86_li](https://user-images.githubusercontent.com/3511727/35657657-835ec4a0-06f5-11e8-91ea-3db18575b58f.jpg)

@shexiaoheng the problem is this?

**Comment by r0adkll** [comment]
You can't specify the `screenOrientation` in the manifest and have to manually apply it in your Activity's `onCreate()` e.g.

```java
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    // fixing portrait mode problem for SDK 26 if using windowIsTranslucent = true
    if (Build.VERSION.SDK_INT == 26) {
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);
    } else {
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
    }        
}
