### ISSUE TITLE
The activity life recycle is confused.

### ISSUE THREAD

**Issue by yeluowuhen52** [r0adkll/Slidr#58]
When I start Activity 2 from Activity 1 .And then slide Activity 2 to finish.
It will call Activity 1's onResume() method first and then Activity 2's onDestroy() instead of  Activity 2's onDestroy() method first and then Activity 1's onResume().
How can I learn about it?

**Comment by bhargavms** [comment]
Android framework DOES NOT guarantee that an activity's `onDestroy()` will be called before a new activities `onResume()`, android framework does not even guarantee that `onDestroy()` will be called (in cases like low memory). So you should technically never depend on `onDestroy()` to perform stop on animations etc. you should do that in `onStop()` of an activity.
May I ask you what you are trying to do in `onDestroy()` ?
