### ISSUE TITLE
Problem with ViewPager

### ISSUE THREAD

**Issue by code4lifevn** [r0adkll/Slidr#6]
In my Activity, I use ViewPager and Slidr can not intercept ViewPager. Please fix it!

**Comment by ladjzero** [comment]
You can listen to OnPageChange event and do lock/unlock Slidr in callback `onPageSelected`.

    @Override
    public void onPageSelected(int i) {
        if (i == 0) slidrInterface.unlock();
        else slidrInterface.lock();
    }

**Comment by r0adkll** [comment]
Please be more specific with the issue. I've tested with ViewPager and Slidr in the same activity and have found my results to work. Closing for now.
