### ISSUE TITLE
Slidr attached to a Chrome Custom Tabs

### ISSUE THREAD

**Issue by bizzbyster** [r0adkll/Slidr#61]
Slidr works great until I click a link that launches a Chrome Custom Tab. At that point, I have to close out the browser window in order to use slider again. Is it possible for Slidr to work with a Chrome Custom Tab? Thanks!

**Comment by r0adkll** [comment]
It is not possible because it requires control of the Activity so it can hijack itself onto the root view. With CCT you don't have control over that at all.

**Comment by Onwa1kenobi** [comment]
Must i call setContentView() on my activity before i can use Slidr? what if I'm creating and adding views dynamically without using setContentView()??
