### ISSUE TITLE
How should I get the coordinates of the finger sliding to the screen

### ISSUE THREAD

**Issue by NeoPi** [r0adkll/Slidr#68]
How should I get the coordinates of the finger sliding to the screen???

**Comment by r0adkll** [comment]
There is not a built-in way to deliver the touch coordinates on the screen at this time. You could manually grab the slider panel and set a non-interrupting touch listener on it and track the touch events.

e.g. _in an Activity_
```java
findViewById(R.id.slidable_panel).setOnTouchListener((v, event) -> {
    float x = event.getX();
    float y = event.getY();
    // Do stuff with event...
    return false;
});
```
