### ISSUE TITLE
overridePendingTransition

### ISSUE THREAD

**Issue by myaghobi** [r0adkll/Slidr#70]
It's great if compatible with:
`overridePendingTransition(R.anim.activity_anim_left, R.anim.activity_anim_right);`

**Comment by r0adkll** [comment]
You can achieve this by implementing the `SlidrListener` in a config that you pass to `Slidr.attach(activity, config)`

Then, do something like this in the `onSlideClosed()` method:

```java
@Override
public boolean onSlideClosed() {
    finish();
    overridePendingTransition(R.anim.activity_anim_left, R.anim.activity_anim_right);
    return true;
}
```
