### ISSUE TITLE
Transparrent background before the soft keyboard appears

### ISSUE THREAD

**Issue by MihailsKuzmins** [r0adkll/Slidr#72]
It is not an issue but rather a help entry.

Use case: when the soft keyboard is opened programmatically, navigating to the next activity, there is a short period when the home screen of Android (desktop screen) is visible.

If someone experiences the same problem, I have solved it by adding a listener to configs, and changing the window color.

1) creating config
SlidrConfig config = new SlidrConfig.Builder()
	.listener(new SlidrListener() {
		private float mPercent;

		@Override
		public void onSlideStateChanged(int state) {
			// means that NavigatingBack, changing the color leads to a flash
			if (mPercent == 0 && state == ViewDragHelper.STATE_IDLE) {
				return;
			}
			ActivityUtils.setAppTheme(BaseActivity.this, state);
		}

		@Override
		public void onSlideChange(float percent) {
			mPercent = percent;
		}

		@Override
		public void onSlideOpened() {}

		@Override
			public void onSlideClosed() {}
		}).build();

2) ActivityUtils.setAppTheme(BaseActivity.this, state) implementation
public static void setAppTheme(Activity activity, int state) {
	// If any color is set in STATE_SETTLING, it leads to a flash
	if (state == ViewDragHelper.STATE_SETTLING) {
		return;
	}

	final @ColorRes int color = getWindowColor(state);
	ColorDrawable colorDrawable = new ColorDrawable(ContextCompat.getColor(activity, color));
	activity.getWindow().setBackgroundDrawable(colorDrawable);
}

3) getWindowColor(state) implementation
@ColorRes
private static int getWindowColor(int state) {
	switch (state) {
		case ViewDragHelper.STATE_IDLE:
			return R.color.colorMaterialLight;
		case ViewDragHelper.STATE_DRAGGING:
			return android.R.color.transparent;
		default:
			String errorMessage = String.format(Locale.getDefault(), "Cannot resolve WindowColor for state: %d", state);
			throw new IllegalArgumentException(errorMessage);
	}
}

I hope it is helpful, but if someone finds a better solution, please share :)

**Comment by Rhtyme** [comment]
@MihailsKuzmins, thanks for your solution, but I think it would be better if we set background of decorView rather than setting background of window directly, so I replaced this:
`activity.getWindow().setBackgroundDrawable(colorDrawable);`
to this:
`activity.getWindow().getDecorView().setBackground(colorDrawable);`

so that we could use this method on the onCreate method of Activity.

**Comment by MihailsKuzmins** [comment]
@Rhtyme interesting idea. Thank you for sharing. I'm not such an Android expert to judge which solution is a better one. Under the hood `getWindow().setBackgroundDrawable(colorDrawable)` calls this bunch of code.
![image](https://user-images.githubusercontent.com/47413092/75179319-7d4edd80-5742-11ea-8edf-c762d07692e0.png)

They call some other methods rather than simply setting the background. But if you solution works as well, I cannot see a reason why not using it :)
