### ISSUE TITLE
[Feature Request] Fragment swipe causes Activity to finish using Jetpack Navigation

### ISSUE THREAD

**Issue by leffsu** [r0adkll/Slidr#76]
When using Jetpack Navigation (2.0.0 and 2.1.0-rc01) when I install swipe on fragment using next lines

`var slidrInterface: SlidrInterface? = null`

   `override fun onResume() {`
        `if (slidrInterface == null)`
            `slidrInterface = Slidr.replace(`
                `view!!.findViewById(R.id.content_container),`
                `SlidrConfig.Builder().position(SlidrPosition.LEFT).build()`
            `)`
        `super.onResume()`
    `},`

swipe does not close the fragment I'm attaching it to, but it closes the activity to which the fragment is attached to.

I do realise that I'm not using advised method of adding fragments using next lines

`getSupportFragmentManager().beginTransaction()
	.add(R.id.fragment_container, YourFragmentClass.newInstance())
	.commit();`

but Jetpack components become more common and I can't think of another library which lets us implement this behaviour without unnecessary hassle.

**Comment by leffsu** [comment]
After further investigation, I've found out that it is impossible during Jetpack not adding a fragment but replacing. The only solution I could find is to manipulate fragments myself.

**Comment by something15525** [comment]
@leffsu I was able to fix this by using a listener on the SlidrConfig.Builder that just pops the backstack on the navcontroller, like so:

`slidrInterface = Slidr.replace(
            oldScreen,
            SlidrConfig.Builder()
                .position(SlidrPosition.LEFT)
                .listener(object : SlidrListener {
                    override fun onSlideClosed() = navController.popBackStack()
                    override fun onSlideStateChanged(state: Int) {}
                    override fun onSlideChange(percent: Float) {}
                    override fun onSlideOpened() {}
                })
                .build()
        )`

**Comment by baonq-2356** [comment]
@something15525 excuse me, what is old screen? do you have a example?
