### ISSUE TITLE
Problem with import BetterRecyclerAdapter;

### ISSUE THREAD

**Issue by Sorush-moradisani** [r0adkll/Slidr#9]
Hi, I  imported com.r0adkll.deadskunk library into my build.gradle but it still has a problem with import com.r0adkll.deadskunk.adapters.BetterRecyclerAdapter; 
![bondage goat zombie](https://cloud.githubusercontent.com/assets/9649165/6412390/614e9e9c-be98-11e4-9153-50ae1fd7bbcd.PNG)

**Comment by r0adkll** [comment]
Can you post your `build.gradle` file here please?

**Comment by Sorush-moradisani** [comment]
![capture2](https://cloud.githubusercontent.com/assets/9649165/6413802/13e23ad2-bea8-11e4-9bb0-d73450962a10.PNG)

**Comment by r0adkll** [comment]
Remove the double import and change it to 

    compile 'com.r0adkll:deadskunk:1.0.4-SNAPSHOT'

as per https://github.com/r0adkll/Slidr/blob/master/example/build.gradle

**Comment by r0adkll** [comment]
Also, is there a reason you manually imported the library + example code into your project AND imported the Slidr library via gradle?

**Comment by Sorush-moradisani** [comment]
Actually I am new to android studio since eclipse is not recommended by google and when I imported the library as module it gave me lots of errors ! and changing double imports to 1.0.4 gave me following error:
![error](https://cloud.githubusercontent.com/assets/9649165/6414478/ff906d7e-beac-11e4-891b-3d3ee53e9d3f.PNG)

**Comment by r0adkll** [comment]
Well you don't need to import the code at all, all you need to use the library is:

    compile 'com.r0adkll:slidableactivity:2.0.2'

and you're good to go.

**Comment by Sorush-moradisani** [comment]
Thanks a lot! It worked :+1:

**Comment by Sorush-moradisani** [comment]
sorry for asking too much but I have another problem :( when I run the application it gives me this error:
![ad](https://cloud.githubusercontent.com/assets/9649165/6425681/8f3ca57a-bf4b-11e4-800b-52363ba38add.PNG)

**Comment by r0adkll** [comment]
in your build.gradle file, change `compile 'com.squareup.dagger:dagger-compiler:1.1.0'`
to `provided 'com.squareup.dagger:dagger-compiler:1.1.0'`

**Comment by Sorush-moradisani** [comment]
THANKS!
